
// This file was auto-generated by ML.NET Model Builder. 

using PalmerPenguins_ConsoleApp;


// Create single instance of sample data from first line of dataset for model input
PalmerPenguins.ModelInput sampleData = new PalmerPenguins.ModelInput()
{
    Island = @"Torgersen",
    Bill_length_mm = 39.5F,
    Bill_depth_mm = 17.4F,
    Flipper_length_mm = 186F,
    Body_mass_g = 3800F,
    Sex = @"female",
    Year = 2007F,
};

// Make a single prediction on the sample data and print results
var predictionResult = PalmerPenguins.Predict(sampleData);

Console.WriteLine("Using model to make single prediction -- Comparing actual Species with predicted Species from sample data...\n\n");


Console.WriteLine($"Species: {@"Adelie"}");
Console.WriteLine($"Island: {@"Torgersen"}");
Console.WriteLine($"Bill_length_mm: {39.5F}");
Console.WriteLine($"Bill_depth_mm: {17.4F}");
Console.WriteLine($"Flipper_length_mm: {186F}");
Console.WriteLine($"Body_mass_g: {3800F}");
Console.WriteLine($"Sex: {@"female"}");
Console.WriteLine($"Year: {2007F}");


Console.WriteLine($"\n\nPredicted Species: {predictionResult.PredictedLabel}\n\n");
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

