﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace PalmerPenguins_WebApi
{
    public partial class PalmerPenguins
    {
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.Categorical.OneHotEncoding(new []{new InputOutputColumnPair(@"island", @"island"),new InputOutputColumnPair(@"sex", @"sex")})      
                                    .Append(mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"bill_length_mm", @"bill_length_mm"),new InputOutputColumnPair(@"bill_depth_mm", @"bill_depth_mm"),new InputOutputColumnPair(@"flipper_length_mm", @"flipper_length_mm"),new InputOutputColumnPair(@"body_mass_g", @"body_mass_g"),new InputOutputColumnPair(@"year", @"year")}))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"island",@"sex",@"bill_length_mm",@"bill_depth_mm",@"flipper_length_mm",@"body_mass_g",@"year"}))      
                                    .Append(mlContext.Transforms.Conversion.MapValueToKey(outputColumnName:@"species",inputColumnName:@"species"))      
                                    .Append(mlContext.Transforms.NormalizeMinMax(@"Features", @"Features"))      
                                    .Append(mlContext.MulticlassClassification.Trainers.OneVersusAll(binaryEstimator: mlContext.BinaryClassification.Trainers.LbfgsLogisticRegression(new LbfgsLogisticRegressionBinaryTrainer.Options(){L1Regularization=0.397552F,L2Regularization=0.03125F,LabelColumnName=@"species",FeatureColumnName=@"Features"}), labelColumnName:@"species"))      
                                    .Append(mlContext.Transforms.Conversion.MapKeyToValue(outputColumnName:@"PredictedLabel",inputColumnName:@"PredictedLabel"));

            return pipeline;
        }
    }
}
